// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiGaugeCircleLeft

#include "../ui.h"
#include "lvgl.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *fuel_arc = NULL;lv_obj_t *ui_Image1 = NULL;

void ui_Screen1_screen_init(void)
{
   LV_FONT_DECLARE(Doto_Extra_Bold_84);
   LV_FONT_DECLARE(Schoolbell_24);
   ui_Screen1 = lv_obj_create(NULL);
   lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

   // lv_obj_set_style_bg_color(ui_Screen1,lv_color_black(),LV_PART_MAIN);

   

   ui_Label1 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label1, 99 );
   lv_obj_set_y( ui_Label1, 115 );
   lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label1,"Oil  Press (PSI)");
   lv_obj_set_style_text_font(ui_Label1, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label2 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label2, 105 );
   lv_obj_set_y( ui_Label2, -31 );
   lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label2,"Fuel  Press (PSI)");
   lv_obj_set_style_text_font(ui_Label2, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label3 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label3, -90 );
   lv_obj_set_y( ui_Label3, 115 );
   lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label3,"Oil  Temp (F)");
   lv_obj_set_style_text_font(ui_Label3, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label4 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label4, -86 );
   lv_obj_set_y( ui_Label4, -31 );
   lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label4,"Water  Temp (F)");
   lv_obj_set_style_text_font(ui_Label4, &Schoolbell_24, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label5 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
   //lv_obj_set_width(ui_Label5, 140);
   lv_label_set_long_mode(ui_Label5, LV_LABEL_LONG_CLIP);
   lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label5, -85 );
   lv_obj_set_y( ui_Label5, -96 );
   lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label5,"0");
   lv_obj_set_style_text_font(ui_Label5, &Doto_Extra_Bold_84, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label6 = lv_label_create(ui_Screen1);
   lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
   //lv_obj_set_width(ui_Label6, 140);
   lv_label_set_long_mode(ui_Label6, LV_LABEL_LONG_CLIP);
   lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label6, 105 );
   lv_obj_set_y( ui_Label6, -96 );
   lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label6,"0");
   lv_obj_set_style_text_font(ui_Label6, &Doto_Extra_Bold_84, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label7 = lv_label_create(ui_Screen1);
   lv_obj_set_width(ui_Label7, 140);
   lv_label_set_long_mode(ui_Label7, LV_LABEL_LONG_CLIP);
   lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label7, -90 );
   lv_obj_set_y( ui_Label7, 50 );
   lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label7,"0");
   lv_obj_set_style_text_font(ui_Label7, &Doto_Extra_Bold_84, LV_PART_MAIN| LV_STATE_DEFAULT);

   ui_Label8 = lv_label_create(ui_Screen1);
   lv_obj_set_width(ui_Label8, 140);
   lv_label_set_long_mode(ui_Label8, LV_LABEL_LONG_CLIP);
   lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
   lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
   lv_obj_set_x( ui_Label8, 105 );
   lv_obj_set_y( ui_Label8, 50 );
   lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
   lv_label_set_text(ui_Label8,"0");
   lv_obj_set_style_text_font(ui_Label8, &Doto_Extra_Bold_84, LV_PART_MAIN| LV_STATE_DEFAULT);

   fuel_arc = lv_arc_create(ui_Screen1);
   lv_obj_set_size(fuel_arc, 480, 480);
   lv_arc_set_rotation(fuel_arc, 135);
   lv_arc_set_bg_angles(fuel_arc, 0, 270);
   lv_arc_set_range(fuel_arc, 0, 100);
   lv_obj_center(fuel_arc);
   lv_arc_set_mode(fuel_arc, LV_ARC_MODE_NORMAL);
   lv_obj_set_style_arc_color(fuel_arc, lv_palette_main(LV_PALETTE_GREEN), LV_PART_INDICATOR);
   lv_obj_set_style_bg_color(fuel_arc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
   lv_obj_set_style_bg_color(fuel_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
   lv_obj_set_style_bg_opa(fuel_arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(fuel_arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
   lv_obj_set_style_arc_opa(fuel_arc, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_bg_opa(fuel_arc, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
   lv_obj_set_style_border_opa(fuel_arc, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
   // lv_obj_set_style_arc_color(fuel_arc, lv_color_black(), LV_PART_MAIN);
   lv_obj_set_style_arc_rounded(fuel_arc, false, LV_PART_MAIN);
   lv_obj_set_style_arc_rounded(fuel_arc, false, LV_PART_INDICATOR);
   lv_obj_set_style_arc_width(fuel_arc, 20, LV_PART_MAIN);
   lv_obj_set_style_arc_width(fuel_arc, 20, LV_PART_INDICATOR);
   lv_obj_remove_style(fuel_arc, NULL, LV_PART_KNOB);
}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_Label3= NULL;
ui_Label4= NULL;
ui_Label5= NULL;
ui_Label6= NULL;
ui_Label7= NULL;
ui_Label8= NULL;

}
